### ISSUE TITLE
error

### ISSUE THREAD

**Issue by shogun88888888** [psliwa/idea-composer-plugin#33]
Note sure what this error even means however here is the log from phpstorm

null
java.lang.NullPointerException
	at org.psliwa.idea.composerJson.util.Files$.loop$1(Files.scala:24)
	at org.psliwa.idea.composerJson.util.Files$.findPath(Files.scala:36)
	at org.psliwa.idea.composerJson.intellij.codeAssist.file.FilePathInspection.pathExists(FilePathInspection.scala:86)
	at org.psliwa.idea.composerJson.intellij.codeAssist.file.FilePathInspection.collectProblems(FilePathInspection.scala:38)
	at org.psliwa.idea.composerJson.intellij.codeAssist.file.FilePathInspection$$anonfun$collectProblems$2.apply(FilePathInspection.scala:32)
	at org.psliwa.idea.composerJson.intellij.codeAssist.file.FilePathInspection$$anonfun$collectProblems$2.apply(FilePathInspection.scala:31)
	at scala.collection.Iterator$class.foreach(Iterator.scala:742)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at org.psliwa.idea.composerJson.intellij.codeAssist.file.FilePathInspection.collectProblems(FilePathInspection.scala:31)
	at org.psliwa.idea.composerJson.intellij.codeAssist.file.FilePathInspection$$anonfun$collectProblems$1$$anonfun$apply$1$$anonfun$apply$2.apply(FilePathInspection.scala:24)
	at org.psliwa.idea.composerJson.intellij.codeAssist.file.FilePathInspection$$anonfun$collectProblems$1$$anonfun$apply$1$$anonfun$apply$2.apply(FilePathInspection.scala:24)
	at scala.Option.foreach(Option.scala:257)
	at org.psliwa.idea.composerJson.intellij.codeAssist.file.FilePathInspection$$anonfun$collectProblems$1$$anonfun$apply$1.apply(FilePathInspection.scala:24)
	at org.psliwa.idea.composerJson.intellij.codeAssist.file.FilePathInspection$$anonfun$collectProblems$1$$anonfun$apply$1.apply(FilePathInspection.scala:23)
	at scala.Option.foreach(Option.scala:257)
	at org.psliwa.idea.composerJson.intellij.codeAssist.file.FilePathInspection$$anonfun$collectProblems$1.apply(FilePathInspection.scala:23)
	at org.psliwa.idea.composerJson.intellij.codeAssist.file.FilePathInspection$$anonfun$collectProblems$1.apply(FilePathInspection.scala:22)
	at scala.collection.Iterator$class.foreach(Iterator.scala:742)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at org.psliwa.idea.composerJson.intellij.codeAssist.file.FilePathInspection.collectProblems(FilePathInspection.scala:22)
	at org.psliwa.idea.composerJson.intellij.codeAssist.file.FilePathInspection$$anonfun$collectProblems$1$$anonfun$apply$1$$anonfun$apply$2.apply(FilePathInspection.scala:24)
	at org.psliwa.idea.composerJson.intellij.codeAssist.file.FilePathInspection$$anonfun$collectProblems$1$$anonfun$apply$1$$anonfun$apply$2.apply(FilePathInspection.scala:24)
	at scala.Option.foreach(Option.scala:257)
	at org.psliwa.idea.composerJson.intellij.codeAssist.file.FilePathInspection$$anonfun$collectProblems$1$$anonfun$apply$1.apply(FilePathInspection.scala:24)
	at org.psliwa.idea.composerJson.intellij.codeAssist.file.FilePathInspection$$anonfun$collectProblems$1$$anonfun$apply$1.apply(FilePathInspection.scala:23)
	at scala.Option.foreach(Option.scala:257)
	at org.psliwa.idea.composerJson.intellij.codeAssist.file.FilePathInspection$$anonfun$collectProblems$1.apply(FilePathInspection.scala:23)
	at org.psliwa.idea.composerJson.intellij.codeAssist.file.FilePathInspection$$anonfun$collectProblems$1.apply(FilePathInspection.scala:22)
	at scala.collection.Iterator$class.foreach(Iterator.scala:742)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at org.psliwa.idea.composerJson.intellij.codeAssist.file.FilePathInspection.collectProblems(FilePathInspection.scala:22)
	at org.psliwa.idea.composerJson.intellij.codeAssist.AbstractInspection$$anonfun$doCheckFile$1$$anonfun$apply$1$$anonfun$apply$2.apply(AbstractInspection.scala:25)
	at org.psliwa.idea.composerJson.intellij.codeAssist.AbstractInspection$$anonfun$doCheckFile$1$$anonfun$apply$1$$anonfun$apply$2.apply(AbstractInspection.scala:24)
	at scala.Option.map(Option.scala:146)
	at org.psliwa.idea.composerJson.intellij.codeAssist.AbstractInspection$$anonfun$doCheckFile$1$$anonfun$apply$1.apply(AbstractInspection.scala:24)
	at org.psliwa.idea.composerJson.intellij.codeAssist.AbstractInspection$$anonfun$doCheckFile$1$$anonfun$apply$1.apply(AbstractInspection.scala:23)
	at scala.Option.flatMap(Option.scala:171)
	at org.psliwa.idea.composerJson.intellij.codeAssist.AbstractInspection$$anonfun$doCheckFile$1.apply(AbstractInspection.scala:23)
	at org.psliwa.idea.composerJson.intellij.codeAssist.AbstractInspection$$anonfun$doCheckFile$1.apply(AbstractInspection.scala:22)
	at scala.Option.flatMap(Option.scala:171)
	at org.psliwa.idea.composerJson.intellij.codeAssist.AbstractInspection.doCheckFile(AbstractInspection.scala:22)
	at org.psliwa.idea.composerJson.intellij.codeAssist.AbstractInspection.checkFile(AbstractInspection.scala:15)
	at com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:156)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:70)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:310)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:123)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1026)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:96)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:106)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:91)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.pollAndExecCC(ForkJoinPool.java:1190)
	at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1879)
	at java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:2045)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:390)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
	at java.util.concurrent.ForkJoinPool.invoke(ForkJoinPool.java:2616)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:60)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:57)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:321)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:229)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:136)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:82)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1026)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:427)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:426)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:154)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by psliwa** [comment]
Thanks, I will check this exception asap. In meantime can you provide PhpStorm and the plugin versions?

**Comment by psliwa** [comment]
Fixed in `1.0.16` version.
