### ISSUE TITLE
In file: LightVirtualFile: \composer.json

### ISSUE THREAD

**Issue by oleg-andreyev** [psliwa/idea-composer-plugin#39]
```
In file: LightVirtualFile: \composer.json
java.lang.NullPointerException
	at org.psliwa.idea.composerJson.intellij.codeAssist.composer.PackageVersionAnnotator.detectUnboundedVersionProblem(PackageVersionAnnotator.scala:65)
	at org.psliwa.idea.composerJson.intellij.codeAssist.composer.PackageVersionAnnotator.detectProblemsInVersion(PackageVersionAnnotator.scala:57)
	at org.psliwa.idea.composerJson.intellij.codeAssist.composer.PackageVersionAnnotator.$anonfun$annotate$3(PackageVersionAnnotator.scala:38)
	at org.psliwa.idea.composerJson.intellij.codeAssist.composer.PackageVersionAnnotator$$Lambda$3208/1269556633.apply(Unknown Source)
	at scala.collection.immutable.List.flatMap(List.scala:324)
	at org.psliwa.idea.composerJson.intellij.codeAssist.composer.PackageVersionAnnotator.$anonfun$annotate$1(PackageVersionAnnotator.scala:37)
	at org.psliwa.idea.composerJson.intellij.codeAssist.composer.PackageVersionAnnotator$$Lambda$3205/2048621567.apply(Unknown Source)
	at scala.collection.immutable.List.flatMap(List.scala:324)
	at org.psliwa.idea.composerJson.intellij.codeAssist.composer.PackageVersionAnnotator.annotate(PackageVersionAnnotator.scala:36)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.a(DefaultHighlightVisitor.java:139)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:363)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:303)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$$Lambda$1290/1453016179.run(Unknown Source)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:322)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:325)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$$Lambda$1294/33977077.run(Unknown Source)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:325)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:237)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:82)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:433)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$$Lambda$1264/1573823580.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1061)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:426)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$$Lambda$1263/665508810.run(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:425)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:405)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:155)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by psliwa** [comment]
Should be fixed in `1.0.19`, let me know if the issue still occurs.
