### ISSUE TITLE
In file: LightVirtualFile: \composer.json

### ISSUE THREAD

**Issue by oleg-andreyev** [psliwa/idea-composer-plugin#46]
PhpStorm 2017.1.4
Build #PS-171.4694.2, built on May 16, 2017
JRE: 1.8.0_112-release-736-b21 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

Version: 1.0.21

Stacktrace:
<details>

```
In file: LightVirtualFile: \composer.json
java.lang.NullPointerException
	at org.psliwa.idea.composerJson.intellij.codeAssist.composer.RepositoryUpdater.$anonfun$getRepositoryUrls$4(RepositoryUpdater.scala:125)
	at scala.Option.map(Option.scala:146)
	at org.psliwa.idea.composerJson.intellij.codeAssist.composer.RepositoryUpdater.mapPath$1(RepositoryUpdater.scala:120)
	at org.psliwa.idea.composerJson.intellij.codeAssist.composer.RepositoryUpdater.$anonfun$getRepositoryUrls$7(RepositoryUpdater.scala:138)
	at org.psliwa.idea.composerJson.intellij.codeAssist.composer.RepositoryUpdater.$anonfun$mapRepositoryElements$5(RepositoryUpdater.scala:88)
	at scala.collection.TraversableLike$WithFilter.$anonfun$flatMap$2(TraversableLike.scala:770)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.collection.TraversableLike$WithFilter.flatMap(TraversableLike.scala:769)
	at org.psliwa.idea.composerJson.intellij.codeAssist.composer.RepositoryUpdater.$anonfun$mapRepositoryElements$2(RepositoryUpdater.scala:86)
	at scala.collection.immutable.List.flatMap(List.scala:335)
	at org.psliwa.idea.composerJson.intellij.codeAssist.composer.RepositoryUpdater.$anonfun$mapRepositoryElements$1(RepositoryUpdater.scala:85)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
	at scala.collection.mutable.ArrayOps$ofRef.flatMap(ArrayOps.scala:191)
	at org.psliwa.idea.composerJson.intellij.codeAssist.composer.RepositoryUpdater.mapRepositoryElements(RepositoryUpdater.scala:84)
	at org.psliwa.idea.composerJson.intellij.codeAssist.composer.RepositoryUpdater.getRepositoryUrls(RepositoryUpdater.scala:138)
	at org.psliwa.idea.composerJson.intellij.codeAssist.composer.RepositoryUpdater.$anonfun$getComposerRepositoryUrls$1(RepositoryUpdater.scala:41)
	at scala.collection.immutable.List.flatMap(List.scala:335)
	at org.psliwa.idea.composerJson.intellij.codeAssist.composer.RepositoryUpdater.getComposerRepositoryUrls(RepositoryUpdater.scala:40)
	at org.psliwa.idea.composerJson.intellij.codeAssist.composer.RepositoryUpdater.annotate(RepositoryUpdater.scala:22)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.a(DefaultHighlightVisitor.java:139)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:368)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:301)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:327)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:330)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:330)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:238)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:83)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:242)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

</details>

**Comment by psliwa** [comment]
Thanks, I will check asap.

**Comment by psliwa** [comment]
Hi, do you have any railable steps to reproduce? When does it happen?

**Comment by oleg-andreyev** [comment]
I'm not 100% sure, but it could be related to Custom Repositories, and when it's configured as `path`

```
"repositories": [
...
{ "type": "path", "url": "./src/<package>" }
...
],
"require": {
...
"<vendor>/package": "dev-master",
...
}
```

**Comment by psliwa** [comment]
It is https://github.com/psliwa/idea-composer-plugin/issues/51 duplication. The fix will be available in the next release.
