### ISSUE TITLE
Short name 'Schema' is not unique (conflict with another plugin)

### ISSUE THREAD

**Issue by venimus** [psliwa/idea-composer-plugin#50]
I get these exceptions for some time

```
Short name 'Schema' is not unique
class 'org.psliwa.idea.composerJson.intellij.codeAssist.schema.SchemaInspection' in PluginDescriptor[name='PHP composer.json support', classpath='C:\Users\██████\.PhpStorm2017.3\config\plugins\composer-json-plugin']
and
class'com.oroplatform.idea.oroplatform.intellij.codeAssist.yml.SchemaInspection' in PluginDescriptor[name='Oro PHPStorm Plugin', classpath='C:\Users\██████\.PhpStorm2017.3\config\plugins\idea-oroplatform-plugin']
conflict [Plugin: org.psliwa.idea.composer]
com.intellij.diagnostic.PluginException: Short name 'Schema' is not unique
class 'org.psliwa.idea.composerJson.intellij.codeAssist.schema.SchemaInspection' in PluginDescriptor[name='PHP composer.json support', classpath='C:\Users\██████\.PhpStorm2017.3\config\plugins\composer-json-plugin']
and
class'com.oroplatform.idea.oroplatform.intellij.codeAssist.yml.SchemaInspection' in PluginDescriptor[name='Oro PHPStorm Plugin', classpath='C:\Users\██████\.PhpStorm2017.3\config\plugins\idea-oroplatform-plugin']
conflict [Plugin: org.psliwa.idea.composer]
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.a(InspectionToolRegistrar.java:86)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.a(InspectionToolRegistrar.java:60)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.createTools(InspectionToolRegistrar.java:127)
	at com.intellij.codeInspection.ex.InspectionSearchableOptionContributor.processOptions(InspectionSearchableOptionContributor.java:34)
	at com.intellij.ide.ui.search.SearchableOptionPreloader.preload(SearchableOptionPreloader.java:49)
	at com.intellij.openapi.application.Preloader.a(Preloader.java:74)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:534)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:479)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.application.Preloader.a(Preloader.java:72)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by psliwa** [comment]
Done, will be fix in the next release.
