### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class org.psliwa.idea.composerJson.Icons

### ISSUE THREAD

**Issue by arunahk** [psliwa/idea-composer-plugin#62]
I keep getting this error when I manually remove the composer lock file and empty the vendor folder.
Plugin Version: 1.0.25

PhpStorm 2018.2 EAP
Build #PS-182.3208.33, built on June 13, 2018
JRE: 1.8.0_152-release-1226-b7 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.13.0-43-generic
```
java.lang.NoClassDefFoundError: Could not initialize class org.psliwa.idea.composerJson.Icons$
	at org.psliwa.idea.composerJson.intellij.filetype.ComposerJsonFileType.getIcon(ComposerJsonFileType.scala:14)
	at com.intellij.ide.presentation.VirtualFilePresentation.getIconImpl(VirtualFilePresentation.java:46)
	at com.intellij.util.IconUtil.getIcon(IconUtil.java:177)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.b(EditorWindow.java:916)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.updateFileIcon(EditorWindow.java:893)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.c(EditorsSplitters.java:338)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.d(EditorsSplitters.java:350)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:232)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:405)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:330)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:371)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.k(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:722)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by lsascha** [comment]
Same issue here which breaks the directory browsing in phpstorm. (stays on 'loading...')
